### ISSUE TITLE
Question api.ai

### ISSUE THREAD

**Issue by Lusitanos67** [Oliv4945/jarvis-api-ai#1]
Salut,

Si je comprends bien c'est ta version de bot, mais comment agrémenter de nouvelles "intents" ?

Merci

**Comment by Oliv4945** [comment]
Il s'agit juste d'un plugin faisant appel à API.ai. Les nouveaux intents sont à faire sur le site, bouton "create intent"

**Comment by Lusitanos67** [comment]
Ah ok donc chacun créé le sien. Je pensais qu'on pouvait en créer un, et ensuite qu'on le partageait à tous pour avoir un large panel de "intents"

**Comment by Oliv4945** [comment]
Il faudrait regarder la doc, il me semble avoir vu que l'on peut exporter les intent, ou au moins les partager
